### PR TITLE
Ingredient import and name regression fixed

### PR DESCRIPTION
**Pull request by BaBrixx**
Created a function for importing categories and importing ingredients

### CODE REVIEW

**Review by atjn — APPROVED** [review]
LGTM!
I am getting a sgementation fault when running the category import, but I think it's fine to merge this now, and fix that error in a later PR :)

**Comment by TSKsmiley** [comment]
> LGTM! I am getting a sgementation fault when running the category import, but I think it's fine to merge this now, and fix that error in a later PR :)

du kan legith ikk LGTM når du har lavet de sidste 4+ commits

**Review by NybyDK — APPROVED** [review]
LVGTMBIIABWWTSF

**Comment by AlbertHald** [comment]
ITHCIVGAITWSSAMI

**Comment by atjn** [comment]
> du kan legith ikk LGTM når du har lavet de sidste 4+ commits
Jov jeg kan så, jeg har bare løst merge conflicts, men jeg synes det da det er en god ide hvis der også er andre der reviewer den :)

**Review by atjn — APPROVED** [review]

**Review by BaBrixx — COMMENTED** [review]
LGTMBPDPMBA

**Review by camillabramsen — APPROVED** [review]
LGTMBPDPMBA

**Pull request merged**
