### PR TITLE
Make algorithm faster

### PR DESCRIPTION
**Pull request by atjn**
MUST GO FASTER

### CODE REVIEW

**Comment by atjn** [comment]
I have not had time to make it look nice, and write proper comments yet, but it should work

**Comment by atjn** [comment]
Now it also looks nice :)

**Review by NybyDK — APPROVED** [review]
srand number is funny number hahaha LOL omegalul roflmfao kekw

EDIT: i can bench on both wsl and windows yesssirrrrrrrr

**Comment by atjn** [comment]
`bench -accuracy` is only used for internal testing, so given our limited timeframe, I think we should let that slide, as long as the actual program runs properly on all machines :)

**Review by BaBrixx — APPROVED** [review]
LGTM!

Ps. Sikke en skov meme med srand funktionen, haha!
Unknown

**Comment by atjn** [comment]
The `bench -accuracy` issue is now tracked in #70

**Pull request merged**
