### PR TITLE
Fix and activate readCategories

### PR DESCRIPTION
**Pull request by atjn**
I have spent more than 6 hours working on this, and then it turns out it was a basic memory management issue that can be fixed with a one-line change.

all-good

### CODE REVIEW

**Comment by NybyDK** [comment]
> I have spent more than 6 hours working on this [...] that can be fixed with a one-line change.

oof

**Comment by atjn** [comment]
PS. This fix is also implemented in #45 :)

**Comment by atjn** [comment]
Damn you, automatic closing algorithm

**Comment by atjn** [comment]
Closed by #45

**Pull request closed without merging**
